### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by deogracia** [hamstah/ukpostcodeparser#5]
Hi,

I clone this repo and I use commit #2f521d8c723e7dc5c38d1c76d5c739a54f8c21d3.

When I run ```python3 setup.py```, I have these following FAIL
```
running build_ext
test_all (ukpostcodeparser.test.parser.TestParser) ... FAIL
test_all (ukpostcodeparser.test.parser.TestParser) ... FAIL

======================================================================
FAIL: test_all (ukpostcodeparser.test.parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lfelicite/Travail/projects/perso/chakra/chakraos-ccr-my-contrib/python3-ukpostcodeparser/src/ukpostcodeparser/ukpostcodeparser/test/parser.py", line 159, in test_all
    self.assertEqual(actual_result, required_result)
AssertionError: ('W1M', '4ZZ') != 'ValueError'

======================================================================
FAIL: test_all (ukpostcodeparser.test.parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lfelicite/Travail/projects/perso/chakra/chakraos-ccr-my-contrib/python3-ukpostcodeparser/src/ukpostcodeparser/ukpostcodeparser/test/parser.py", line 159, in test_all
    self.assertEqual(actual_result, required_result)
AssertionError: ('W1M', '4ZZ') != 'ValueError'

----------------------------------------------------------------------
Ran 2 tests in 0.011s

FAILED (failures=2)

```

I got the same error if I use the latest commit ( #4040f2cdbf884e41a336271a0d654e785953b44b)

Did I do something the wrong way?

**Comment by hamstah** [comment]
Hi,

I don't think you've done anything wrong.
It looks like the test might be out of date and you should be ok using it.
There have been a few changes since the first commit which had the test.
I'll have a look when I get some time.

Thanks

**Comment by deogracia** [comment]
OK.

Thanks for your work :D

**Comment by siddharthist** [comment]
It looks like there's been a PR related to this issue, but there hasn't been a new version uploaded to PyPI.

**Comment by hamstah** [comment]
Hi,
I've updated Pypi with master just now.
Sorry for the delay in updating it, got busy and completely forgot!
